"""
LLM-based document extractor using OpenRouter API.
Takes OCR text and structures it into tracker-compatible JSON.
"""

import json
import re
from openai import OpenAI
from config import COLUMN_MAPPINGS, EXPECTED_DOCUMENTS, get_extraction_fields


def _build_system_prompt(case_number: int) -> str:
    """Build the system prompt for a given case number."""
    fields = get_extraction_fields(case_number)
    expected_docs = EXPECTED_DOCUMENTS[case_number]

    fields_json = json.dumps(fields, indent=2)
    docs_list = "\n".join(f"  - {d}" for d in expected_docs)

    return f"""You are an expert document data extractor for Indian solar energy procurement documents.
You will receive OCR-extracted text from a PDF containing multiple documents related to Case {case_number} procurement.

The PDF may contain the following document types:
{docs_list}

Your task is to extract structured data and return it as a JSON object.

IMPORTANT RULES:
1. Return ONLY valid JSON - no markdown, no explanation, no code blocks.
2. Use null for any field that cannot be found in the documents.
3. For Yes/No fields (like "packing_list_available", "bl_available", etc.): set "Yes" if that document type was found in the PDF, "No" if not found.
4. For date fields, use DD.MM.YYYY format.
5. For amount fields, return numeric values (no currency symbols or commas).
6. For quantity fields, return numeric values.
7. If multiple vehicles/LRs are found, return the transportation fields as arrays (e.g., "lr_vehicle_no": ["GJ12BZ7766", "GJ39T6310"]). IMPORTANT: Only include UNIQUE values — do NOT repeat the same vehicle number, LR number, or gate entry number multiple times. Each array entry must represent a distinct vehicle/delivery.
8. Cross-reference linkage fields should match values from the source documents (e.g., boe_ci_number_linkage should contain the commercial invoice number found in the BoE).

The JSON must use these exact field names as keys:
{fields_json}

Return a single flat JSON object with these keys."""


def _build_case1_user_prompt(text: str) -> str:
    return f"""Extract data from the following OCR text of a Case 1 PDF (Import - EPC Clearance + Domestic Sale to SPV).

This PDF should contain: Commercial Invoice (from foreign supplier), Packing List, Certificate of Origin, Bill of Lading, Bill of Entry (customs), Duty Payment Challan, E-way Bill, Tax Invoice (EPC to SPV domestic sale), E-Invoice/IRN, LR/Lorry Receipt, and GRN.

Key sections to fill:
- Commercial Invoice Details: invoice number, item description, date, bill-to/ship-to parties, quantity
- BoE Details: BL number, BOE number, item description, date, quantity, amounts (assessable, BCD, ADD, IGST), duty challan, seller/buyer names
- E-way Bill: bill number, generated by, GSTIN, item, qty, type (detailed/normal), from/to addresses, values
- Tax Invoice (EPC→SPV): invoice number, item, parties, IRN, date, quantity, GST rate, amounts, TCS
- Transportation: LR details, container number, vehicle number, transporter, gate entry, GRN

OCR TEXT:
{text}"""


def _build_case2_user_prompt(text: str) -> str:
    return f"""Extract data from the following OCR text of a Case 2 PDF (Import - HSS + SPV Custom Clearance).

This PDF should contain: Commercial Invoice (from foreign supplier), Packing List, Certificate of Origin, HSS Invoice (EPC to SPV), HSS Agreement, Bill of Lading, Bill of Entry (cleared by SPV), Duty Payment Challan, E-way Bill, LR/Lorry Receipt, and GRN.

Key sections to fill:
- Commercial Invoice Details: invoice number, item description, date, parties, quantity
- HSS Invoice: HSS invoice number, item, parties, date, quantity, value
- HSS Agreement: agreement number, item description, referenced invoice/BL numbers, buyer name
- BoE Details: BL number, BOE number, item, date, quantity, amounts, duty challan, seller/buyer
- E-way Bill: bill number, BOE linkage, generated by, GSTIN, item, qty, type, addresses, values
- Transportation: LR details, container, vehicle, transporter, gate entry, GRN

OCR TEXT:
{text}"""


def _build_case3_user_prompt(text: str) -> str:
    return f"""Extract data from the following OCR text of a Case 3 PDF (Domestic Purchase + Sale to SPV).

This PDF should contain: Commercial/Tax Invoice #1 (Supplier to EPC), Packing List, E-Invoice/IRN, E-way Bill, Tax Invoice #2 (EPC to SPV), LR/Lorry Receipt, and GRN.

Key sections to fill:
- Commercial Invoice (first tax invoice - supplier to EPC): invoice number, item, parties (bill from/to, ship to), place of supply, IRN, date, quantity, GST rate, amounts, TCS
- E-way Bill: bill number, invoice linkage, generated by, GSTIN, item, qty, type, addresses, values
- Tax Invoice (second - EPC to SPV): invoice number, item, parties, place of supply, IRN, date, quantity, GST rate, amounts, TCS
- Transportation: LR details, container, vehicle, transporter, gate entry, GRN

NOTE: Case 3 has TWO tax invoices. The first (commercial_invoice/ci_ fields) is from the supplier to EPC. The second (tax_invoice/ti_ fields) is from EPC to SPV.

OCR TEXT:
{text}"""


USER_PROMPT_BUILDERS = {
    1: _build_case1_user_prompt,
    2: _build_case2_user_prompt,
    3: _build_case3_user_prompt,
}


class DocumentExtractor:
    def __init__(self, api_key: str, model: str = "google/gemini-2.0-flash-001"):
        self.client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=api_key,
        )
        self.model = model

    def extract(self, combined_text: str, case_number: int) -> dict:
        """
        Send OCR text to LLM and get structured JSON back.

        Args:
            combined_text: Combined OCR text with page markers.
            case_number: 1, 2, or 3.

        Returns:
            Dict of extracted fields.
        """
        system_prompt = _build_system_prompt(case_number)
        user_prompt = USER_PROMPT_BUILDERS[case_number](combined_text)

        # If text is very long, we may need to chunk it
        # OpenRouter models typically support 128k+ context
        # Truncate if extremely long (>200k chars)
        if len(user_prompt) > 200000:
            user_prompt = user_prompt[:200000] + "\n\n[TEXT TRUNCATED DUE TO LENGTH]"

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.1,
            max_tokens=8000,
        )

        raw_response = response.choices[0].message.content

        # Parse JSON from response - handle potential markdown wrapping
        return self._parse_json_response(raw_response)

    def _parse_json_response(self, raw: str) -> dict:
        """Parse JSON from LLM response, handling markdown code blocks."""
        # Try direct parse first
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            pass

        # Try extracting from markdown code block
        match = re.search(r"```(?:json)?\s*\n?(.*?)\n?```", raw, re.DOTALL)
        if match:
            try:
                return json.loads(match.group(1))
            except json.JSONDecodeError:
                pass

        # Try finding JSON object in the text
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            try:
                return json.loads(match.group(0))
            except json.JSONDecodeError:
                pass

        raise ValueError(f"Could not parse JSON from LLM response:\n{raw[:500]}")
